services:
  mysql:
    ports:
      - "3306:3306"

  redis:
    ports:
      - "6379:6379"

  corebank-service:
    ports:
      - "8081:8081"

  fep-gateway:
    ports:
      - "8083:8083"

  fep-simulator:
    ports:
      - "8082:8082"
