#!/usr/bin/env bash
set -euo pipefail

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS channel_db;
CREATE DATABASE IF NOT EXISTS core_db;
CREATE DATABASE IF NOT EXISTS fep_gateway_db;
CREATE DATABASE IF NOT EXISTS fep_simulator_db;
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON channel_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON core_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON fep_gateway_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON fep_simulator_db.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
